database.url=jdbc:mysql://localhost:3306/mindaudit_java
database.user=root
database.password=
app.name=MindAudit
app.version=1.0.0
app.description=Système de Gestion d'Audit Interne

# Email Configuration (Brevo SMTP)
mail.smtp.host=smtp-relay.brevo.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=a9ed33001@smtp-brevo.com
mail.password=xsmtpsib-d19520d9c13a997014f724c84ec0092193da0d5e8a2eb2b0635a193be4e05462-emJbDQN5qnOQudBC
mail.admin.target=eleammar21@gmail.com
mail.from=eleammar21@gmail.com